-- ============================================================
-- FinPay V2
-- V002 - OTP Onboarding Infrastructure
-- ============================================================
--
-- Purpose:
--   Provide secure, auditable OTP verification records for
--   customer onboarding and account-security workflows.
--
-- Design principles:
--   - Never store plaintext OTP codes.
--   - OTP records belong to a specific user.
--   - Expiration and attempt tracking are database-backed.
--   - Contact verification remains separate from identity/KYC.
-- ============================================================

CREATE TABLE public.otp_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    channel VARCHAR(20) NOT NULL,

    purpose VARCHAR(30) NOT NULL,

    code_hash VARCHAR(255) NOT NULL,

    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    attempts INTEGER NOT NULL DEFAULT 0,

    verified_at TIMESTAMP WITHOUT TIME ZONE NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_otp_verifications_user
        FOREIGN KEY (user_id)
        REFERENCES public.users(id)
        ON DELETE CASCADE,

    CONSTRAINT otp_verifications_channel_check
        CHECK (
            channel IN (
                'EMAIL',
                'SMS'
            )
        ),

    CONSTRAINT otp_verifications_purpose_check
        CHECK (
            purpose IN (
                'REGISTRATION',
                'LOGIN',
                'PASSWORD_RESET',
                'PHONE_VERIFICATION',
                'EMAIL_VERIFICATION'
            )
        ),

    CONSTRAINT otp_verifications_status_check
        CHECK (
            status IN (
                'PENDING',
                'VERIFIED',
                'EXPIRED',
                'FAILED',
                'CANCELLED'
            )
        ),

    CONSTRAINT otp_verifications_attempts_check
        CHECK (attempts >= 0)
);

CREATE INDEX idx_otp_verifications_user_id
    ON public.otp_verifications (user_id);

CREATE INDEX idx_otp_verifications_user_status
    ON public.otp_verifications (user_id, status);

CREATE INDEX idx_otp_verifications_expires_at
    ON public.otp_verifications (expires_at);

CREATE INDEX idx_otp_verifications_purpose
    ON public.otp_verifications (purpose);
