spring.application.name=FinPay API

# Database
spring.datasource.url=jdbc:postgresql://localhost:5434/finpay
spring.datasource.username=finpay
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Server
server.port=8080
logging.level.org.springframework.security=INFO
# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000


# M-Pesa Daraja configuration
mpesa.base-url=${MPESA_BASE_URL:https://sandbox.safaricom.co.ke}
mpesa.consumer-key=${MPESA_CONSUMER_KEY}
mpesa.consumer-secret=${MPESA_CONSUMER_SECRET}
mpesa.shortcode=${MPESA_SHORTCODE}
mpesa.passkey=${MPESA_PASSKEY}
mpesa.callback-url=${MPESA_CALLBACK_URL}
