spring.application.name=FinPay API

# Database
spring.datasource.url=jdbc:postgresql://localhost:5434/finpay
spring.datasource.username=finpay
spring.datasource.password=finpay_dev_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080
logging.level.org.springframework.security=DEBUG
# JWT Configuration
jwt.secret=FinPaySecretKeyForJwtAuthentication2026VerySecureKey
jwt.expiration=3600000
